### ISSUE TITLE
disappearing zones after upgrade to m21lx.0

### ISSUE THREAD

**Issue by bamdadkhan** [tribblix/tribblix-release#1]
as the title says, after upgrading zoneadm shows nothing aside from the global zone:
```
# zoneadm list -iv
  ID NAME             STATUS     PATH                           BRAND    IP
   0 global           running    /                              ipkg     shared
```
zone configuration files are there:
```
# ls /etc/zones
BAALZLX01.xml       SUNWblank.xml       SUNWsolaris10.xml   did.txt
BAALZS10.xml        SUNWdefault.xml     TRIBalien.xml       index
BAALZS20.xml        SUNWlx.xml          TRIBsparse.xml      index.pre-upgrade
BAALZSVB.xml        SUNWsn1.xml         TRIBwhole.xml
```
however, exporting them yields a strange error:
```
# zonecfg -z BAALZSVB export | tail -3
The administrative rights were updated to match the current RBAC configuration.
Use "info admin" and "revert" to compare with the previous settings.
BAALZSVB: Problem updating index file
Configuration not saved.
set user=bamdad
set auths=manage
end
```

what am i doing wrong?

best,
bamdad

**Comment by ptribble** [comment]
The simplest way, which ought to work if all the zones are LX zones, is to

cp index.pre-upgrade index
svcadm restart zones

At the moment, regular zones will be broken if you upgrade, but LX zones (and solaris10 zones, come to that) are logically independent from the operating system in the global zone.

**Comment by bamdadkhan** [comment]
yep i read the part about lx zones. the thing is, only one of them is of lx brand. i had one tribblix zone (whole root i think) and two s10 zones. i think the db that zoneadm uses is messed up, but (shame on me) i don't know where that's stored.

**Comment by ptribble** [comment]
If you look at /etc/zones/index.pre-upgrade, it will list the zones. You're safe copying the lines for the LX and solaris10 zone and putting them on the end of the index file.

The whole root zone might work, it  would just be a different type of alien zone. Sparse root zones absolutely won't work.

**Comment by bamdadkhan** [comment]
wow, i feel like an idiot now. : ) thank you. fixed.

**Comment by ptribble** [comment]
Not at all. I could fix this in the upgrader, I think, and probably should.

**Comment by bamdadkhan** [comment]
one last question related to this: is there a way to properly upgrade a whole-root zone? `zap upgrade $release` works but creates a new bootenv which fails to boot even after setting its 'mountpoint' to 'legacy'.

what i mean to say is that is there a `zap upgrade` switch that skips the new boot environment creation?
